// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/bot-commands': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bot-commands.post').default>>>>
    }
    '/api/bot-config': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bot-config.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bot-config.post').default>>>>
    }
    '/api/bot-register-user': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bot-register-user.post').default>>>>
    }
    '/api/bot-reload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bot-reload.post').default>>>>
    }
    '/api/bot-set-balance': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bot-set-balance.post').default>>>>
    }
    '/api/bot-status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bot-status.get').default>>>>
    }
    '/api/bot-update-balance': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bot-update-balance.post').default>>>>
    }
    '/api/bot-user-data': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bot-user-data.get').default>>>>
    }
    '/api/db-config': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/db-config.get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/db-config.put').default>>>>
    }
    '/api/debug-users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/debug-users.get').default>>>>
    }
    '/api/health': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/health.get').default>>>>
    }
    '/api/import-users': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/import-users.post').default>>>>
    }
    '/api/keyword-replies': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/keyword-replies.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/keyword-replies.post').default>>>>
    }
    '/api/license/activate-order': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/license/activate-order.post').default>>>>
    }
    '/api/license/deactivate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/license/deactivate.post').default>>>>
    }
    '/api/license/info': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/license/info.get').default>>>>
    }
    '/api/license/validate-order': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/license/validate-order.post').default>>>>
    }
    '/api/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/login.post').default>>>>
    }
    '/api/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/logout.post').default>>>>
    }
    '/api/orders': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders.get').default>>>>
    }
    '/api/restart-bot': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/restart-bot.post').default>>>>
    }
    '/api/stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stats.get').default>>>>
    }
    '/api/system-users': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system-users.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system-users.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system-users.post').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system-users.put').default>>>>
    }
    '/api/system-users/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system-users/[id].get').default>>>>
    }
    '/api/system/check-update-folder': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/check-update-folder.get').default>>>>
    }
    '/api/system/folder-status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/folder-status.get').default>>>>
    }
    '/api/system/restart': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/restart.post').default>>>>
    }
    '/api/system/simple-download': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/simple-download.post').default>>>>
    }
    '/api/system/update-apply': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/update-apply.post').default>>>>
    }
    '/api/system/update-auto-apply': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/update-auto-apply.post').default>>>>
    }
    '/api/system/update-backup': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/update-backup.post').default>>>>
    }
    '/api/system/update-check-files': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/update-check-files.get').default>>>>
    }
    '/api/system/update-check-permissions': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/update-check-permissions.post').default>>>>
    }
    '/api/system/update-download': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/update-download.post').default>>>>
    }
    '/api/system/update-extract': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/update-extract.post').default>>>>
    }
    '/api/system/update-history': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/update-history.get').default>>>>
    }
    '/api/system/update-progress': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/update-progress.get').default>>>>
    }
    '/api/system/update-scheduler': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/update-scheduler.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/update-scheduler.post').default>>>>
    }
    '/api/system/update-state': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/update-state').default>>>>
    }
    '/api/system/version-check': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/version-check.get').default>>>>
    }
    '/api/tg-users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tg-users.get').default>>>>
    }
    '/api/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
  }
}
export {}