// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/bot-commands': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bot-commands.post').default>>>>
    }
    '/api/bot-config': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bot-config.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bot-config.post').default>>>>
    }
    '/api/bot-status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bot-status.get').default>>>>
    }
    '/api/check-licenses-table': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/check-licenses-table.get').default>>>>
    }
    '/api/debug-users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/debug-users.get').default>>>>
    }
    '/api/import-users': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/import-users.post').default>>>>
    }
    '/api/init-licenses-table': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/init-licenses-table.post').default>>>>
    }
    '/api/keyword-replies': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/keyword-replies.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/keyword-replies.post').default>>>>
    }
    '/api/license/activate-order': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/license/activate-order.post').default>>>>
    }
    '/api/license/deactivate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/license/deactivate.post').default>>>>
    }
    '/api/license/info': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/license/info.get').default>>>>
    }
    '/api/license/update': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/license/update.post').default>>>>
    }
    '/api/license/upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/license/upload.post').default>>>>
    }
    '/api/license/validate-order': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/license/validate-order.post').default>>>>
    }
    '/api/license/validate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/license/validate.post').default>>>>
    }
    '/api/license/verify': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/license/verify.post').default>>>>
    }
    '/api/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/login.post').default>>>>
    }
    '/api/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/logout.post').default>>>>
    }
    '/api/orders': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders.get').default>>>>
    }
    '/api/orders/retry': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders/retry.post').default>>>>
    }
    '/api/restart-bot': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/restart-bot.post').default>>>>
    }
    '/api/stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stats.get').default>>>>
    }
    '/api/system-users': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system-users.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system-users.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system-users.post').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system-users.put').default>>>>
    }
    '/api/system-users/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system-users/[id].get').default>>>>
    }
    '/api/system/restart': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/restart.post').default>>>>
    }
    '/api/system/update-apply': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/update-apply.post').default>>>>
    }
    '/api/system/update-backup': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/update-backup.post').default>>>>
    }
    '/api/system/update-download': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/update-download.post').default>>>>
    }
    '/api/system/update-extract': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/update-extract.post').default>>>>
    }
    '/api/system/update-progress': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/update-progress.get').default>>>>
    }
    '/api/system/version-check': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/version-check.get').default>>>>
    }
    '/api/test-db': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/test-db.get').default>>>>
    }
    '/api/tg-users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tg-users.get').default>>>>
    }
    '/api/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
  }
}
export {}